dataset:
  batch_size: 40
  corpus:
    dev_path: dev.conllx
    root: data/ctb
    test_path: test.conllx
    train_path: train.conllx
  embeddings:
    dev_path: dev.bertbase-layers.hdf5
    root: data/ctb
    test_path: test.bertbase-layers.hdf5
    train_path: train.bertbase-layers.hdf5
    type: subword
  observation_fieldnames:
  - index
  - sentence
  - lemma_sentence
  - upos_sentence
  - xpos_sentence
  - morph
  - head_indices
  - governance_relations
  - secondary_relations
  - extra_info
  - embeddings
model:
  hidden_dim: 768
  model_layer: 11
  model_type: BERT-disk
  use_disk: true
probe:
  diagonal: false
  maximum_rank: 128
  params_path: predictor_11_parse-depth.params
  psd_parameters: true
  task_name: parse-depth
  task_signature: word
probe_training:
  epochs: 30
  loss: L1
reporting:
  observation_paths:
    dev_path: dev.observations
    test_path: test.observations
    train_path: train.observations
  prediction_paths:
    dev_path: dev.predictions
    test_path: test.predictions
    train_path: train.predictions
  reporting_methods:
  - spearmanr
  - root_acc
  root: results
